POS.CobaLagi.Web/Controllers/OrderDetailController.cs
using Microsoft.AspNetCore.Mvc;
using POS.CobaLagi.Repository;
using POS.CobaLagi.Service;
using POS.CobaLagi.ViewModel;

namespace POS.Web.Controllers
{
    public class OrderDetailController : Controller
    {
        private readonly OrderDetailService _service;

        public OrderDetailController(ApplicationDbContext context)
        {
            _service = new OrderDetailService(context);
        }

        [HttpGet]
        public ActionResult Index()
        {
            var Data = _service.GetAll();
            return View(Data);
        }

        [HttpGet]
        public IActionResult Detail(int id)
        {
            var Data = _service.GetById(id);
            return View(Data);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpGet]
        public IActionResult ModalAdd()
        {
            return PartialView("_Create");
        }


        [HttpGet]
        public IActionResult Edit(int id)
        {
            var Data = _service.GetById(id);
            return View(Data);
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            _service.Delete(id);
            return Redirect("/OrderDetail");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("OrderId, ProductId, UnitPrice, Quantity, Discount")] OrderDetailModel request)
        {
            if (ModelState.IsValid)
            {
                _service.Create(request);
                return Redirect("/OrderDetail");
            }
            return View(request);
        }

        [HttpPost]
        public IActionResult Update([Bind("Id, OrderId, ProductId, UnitPrice, Quantity, Discount")] OrderDetailModel request)
        {
            if (ModelState.IsValid)
            {
                _service.Update(request);
                return Redirect("/OrderDetail");
            }
            return View("Edit", request);
        }
    }
}

POS.CobaLagi.Web/Views/OrderDetail/Create.cshtml
@using POS.CobaLagi.ViewModel;
@model OrderDetailModel

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>Add New OrderDetail</h2>
<form asp-controller="OrderDetail" asp-action="Create" method="post">
    <div asp-validation-summary="All"></div>
    <div class="form-group">
        <label asp-for="OrderId"></label>
        <input asp-for="OrderId" class="form-control" />
        <span asp-validation-for="OrderId" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="ProductId"></label>
        <input asp-for="ProductId" class="form-control" />
        <span asp-validation-for="ProductId" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="UnitPrice"></label>
        <input asp-for="UnitPrice" class="form-control" />
        <span asp-validation-for="UnitPrice" class="text-danger"></span>
    </div>

        <div class="form-group">
        <label asp-for="Quantity"></label>
        <input asp-for="Quantity" class="form-control" />
        <span asp-validation-for="Quantity" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Discount"></label>
        <input asp-for="Discount" class="form-control" />
        <span asp-validation-for="Discount" class="text-danger"></span>
    </div>

    <div class="form-footer">
        <button type="submit" class="btn btn-primary">Save</button>
    </div>
</form>

POS.CobaLagi.Web/Views/OrderDetail/Detail.cshtml
@using POS.CobaLagi.Repository;
@model OrderDetailEntity
@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>Detail OrderDetail</h2>
<table class="table table-bordered">
    <tr>
        <th>Id</th>
        <td>@Model.Id</td>
    </tr>
    <tr>
        <th>OrderId</th>
        <td>@Model.OrderId</td>
    </tr>
    <tr>
        <th>ProductId</th>
        <td>@Model.ProductId</td>
    </tr>

    <tr>
        <th>UnitPrice</th>
        <td>@Model.UnitPrice</td>
    </tr>
    <tr>
        <th>Quantity</th>
        <td>@Model.Quantity</td>
    </tr>
    <tr>
        <th>Discount</th>
        <td>@Model.Discount</td>
    </tr>
</table>

<a class="btn btn-sm btn-primary" asp-area="" asp-controller="OrderDetail" asp-action="OrderDetail">Back</a>

POS.CobaLagi.Web/Views/OrderDetail/Edit.cshtml
@using POS.CobaLagi.Repository;
@model OrderDetailEntity

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>Edit OrderDetail</h2>
<form asp-controller="OrderDetail" asp-action="Update" method="post">
    <input type="hidden" asp-for="Id" />

    <div asp-validation-summary="All"></div>
    <div class="form-group">
        <label asp-for="OrderId"></label>
        <input asp-for="OrderId" class="form-control" />
        <span asp-validation-for="OrderId" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="ProductId"></label>
        <input asp-for="ProductId" class="form-control" />
        <span asp-validation-for="ProductId" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="UnitPrice"></label>
        <input asp-for="UnitPrice" class="form-control" />
        <span asp-validation-for="UnitPrice" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Quantity"></label>
        <input asp-for="Quantity" class="form-control" />
        <span asp-validation-for="Quantity" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Discount"></label>
        <input asp-for="Discount" class="form-control" />
        <span asp-validation-for="Discount" class="text-danger"></span>
    </div>

    <div class="form-footer">
        <button type="submit" class="btn btn-warning">Update</button>
    </div>
</form>

POS.CobaLagi.Web/Views/OrderDetail/Index.cshtml
@using POS.CobaLagi.Repository;
@model IEnumerable<OrderDetailEntity>

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>OrderDetail Get All</h2>
<a class="btn btn-sm btn-primary" asp-area="" asp-controller="OrderDetail" asp-action="Create" id="btn-add">Create New OrderDetail</a>
<table class="table table-responsive">
    <thead>
        <tr>
            <th>Id</th>
            <th>OrderId</th>
            <th>ProductId</th>
            <th>UnitPrice</th>
            <th>Quantity</th>
            <th>Discount</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.OrderId</td>
                <td>@item.ProductId</td>
                <td>@item.UnitPrice</td>
                <td>@item.Quantity</td>
                <td>@item.Discount</td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-sm btn-warning">Edit</a>
                    <a asp-action="Detail" asp-route-id="@item.Id" class="btn btn-sm btn-success">Detail</a>
                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-sm btn-danger">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

<div id="my-modal" class="modal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Create Order Detail</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>Modal body text goes here.</p>
            </div>

        </div>
    </div>
</div>

@section Scripts
    {
    <script type="text/javascript">
        $("#btn-add").on("click", function (e) {
            e.preventDefault();
            //alert("Ah ... kamu kok sentuh aku");
            $.ajax({
                url: "/OrderDetail/ModalAdd",
                type: "GET",
                dataType: "HTML",
                success: function (data) {
                    $("#my-modal").find(".modal-body").html(data);
                    $("#my-modal").modal("show");
                }
            });
        });</script>
}

POS.CobaLagi.Web/Views/OrderDetail/_Create.cshtml
@using POS.CobaLagi.ViewModel;
@model OrderDetailModel

<form asp-controller="OrderDetail" asp-action="Create" method="post">
    <div asp-validation-summary="All"></div>
    <div class="form-group">
        <label asp-for="OrderId"></label>
        <input asp-for="OrderId" class="form-control" />
        <span asp-validation-for="OrderId" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="ProductId"></label>
        <input asp-for="ProductId" class="form-control" />
        <span asp-validation-for="ProductId" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="UnitPrice"></label>
        <input asp-for="UnitPrice" class="form-control" />
        <span asp-validation-for="UnitPrice" class="text-danger"></span>
    </div>

        <div class="form-group">
        <label asp-for="Quantity"></label>
        <input asp-for="Quantity" class="form-control" />
        <span asp-validation-for="Quantity" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Discount"></label>
        <input asp-for="Discount" class="form-control" />
        <span asp-validation-for="Discount" class="text-danger"></span>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Create</button>
    </div>
</form>